global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval:  5s
    static_configs:
      - targets: ['prom:9090']
  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets: ['grafana:3000']
  - job_name: 'web'
    scrape_interval: 30s
    scrape_timeout: 20s
    static_configs:
      - targets: [
        'host.docker.internal:82']
  - job_name: pushgateway
    honor_timestamps: true
    scrape_interval: 6s
    scrape_timeout: 5s
    metrics_path: /prom-pushgateway/metrics
    scheme: https
    static_configs:
    - targets:
      - ln-services.dvm.costar.com
      labels:
        environment: DVM
        vertical: LN
  # - job_name: 'wmi-exporter'
  #   scrape_interval:  5s
  #   static_configs:
  #     - targets: ['192.168.0.84:9182']
