global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval:  5s
    static_configs:
      - targets: ['prom:9090']
  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets: ['grafana:3000']
  - job_name: 'wmi-exporter'
    scrape_interval:  5s
    static_configs:
      - targets: ['192.168.0.84:9182']


