global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval:  5s
    static_configs:
      - targets: ['prom:9090']
  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets: ['grafana:3000']
  - job_name: 'web'
    scrape_interval: 30s
    scrape_timeout: 20s
    static_configs:
      - targets: ['host.docker.internal:82','LN01WEBNTSM501:80','LN01WEBNTSM502:80','LN04WEBNTSM501:80','LN04WEBNTSM502:80','LN01WEBNTSM601:80','LN01WEBNTSM602:80','LN04WEBNTSM601:80','LN04WEBNTSM602:80']
  # - job_name: 'wmi-exporter'
  #   scrape_interval:  5s
  #   static_configs:
  #     - targets: ['192.168.0.84:9182']
